### ISSUE TITLE
Test failure reporting for external assertion libraries

### ISSUE THREAD

**Issue by NoelAbrahams** [connor4312/nodejs-testing#16]
Suppose we have a wrapper around the NodeJS assertions library:

```js
// src/lib/my-assertions.js

const { strictEqual } = require("assert");

function isTrue(value) {
 assert.strictEqual(value, true);
}
```

And somewhere else we have some test cases:

```js
// src/tests/my-tests.js

const { strictEqual } = require("assert");
const { isTrue } = require('../lib/my-assertions')

describe('foo tests', () => {

    const myValue = false;

    it('Test A', () => {
        isTrue(myValue);
    });

    it('Test B', () => {
        strictEqual(myValue, true);
    });
});
```

The user experience from the two failed assertions is quite difference. When Test B fails, the error is reported at the site of the test case itself.

However,  when Test A fails the error is reported in file `my-assertions.js`.

![image](https://github.com/connor4312/nodejs-testing/assets/1106823/5f7f5fd3-d59b-4f38-b39b-41b2e5ccc4ab)

IMO Test B is the better UX: we would ideally want to know the context in which the test failed, rather than the standard source of the assertion library.

I'm not sure whether this is fixable. Perhaps there could be a way to tell the extension that we are using some sort of assertion library?

**Comment by connor4312** [comment]
We could add configuration for this. But you can also manipulate the stacktrace of the returned error so that the caller's line is at the top of the error's stacktrace. That's used for determining what location to jump to. Such manipulation is nice even to the CLI invoker of tests since there's less noise in the stack.

Here's one example where I do something like this in vscode: https://github.com/microsoft/vscode/blob/ae33b4889e12a156e72b06afc17f635dc00986db/src/vs/base/test/common/snapshot.ts#L78-L84

**Comment by NoelAbrahams** [comment]
Thanks for the tip. Yes, that worked for me:

```ts
export function isTrue(value) {
    if (value !== true) {
        const error = new Error(`Expected value to be true. Actual '${String(value)}'`);
        error.stack = (error.stack || '').split('\n').slice(2).join('\n');
        throw error;
    }
}
```

I'm going to close this, as our use case is fixable. This could still be a problem for people who have no control over their assertion library. But could be revisited.
