### ISSUE TITLE
Typescript "as const" may break tree parsing

### ISSUE THREAD

**Issue by yleflour** [connor4312/nodejs-testing#51]
I encountered a weird bug:

```
import assert from "node:assert/strict";
import { describe, it } from "node:test";

describe("A", () => {
  describe("A.1", () => {
    it("works", async () => {
      assert.equal(1, 1);
    });

    it("breaks the tree", async () => {
      const plop = `Hello ${{ type: "extra" } as const} World`;
      assert.equal(1, 1);
    });
  });

  describe("A.2", () => {
    it("doesn't show", async () => {
      assert.equal(1, 1);
    });
  });
});
```

Produces the following tree:
<img width="212" alt="image" src="https://github.com/user-attachments/assets/72a2d64c-f037-489b-a538-0ed3a502e702">

The issue comes from `${{ type: "extra" } as const}` and the following rewrites work:
- Using`${{ type: "extra" as const }}`
- Declaring `const inlineObj = { type: "extra" } as const` and `${inlineObj}`

**Comment by yleflour** [comment]
Just got a minimal sample repo set up here: https://github.com/yleflour/nodejs-testing-demo
I'll check out the built JS. if I have time

**Comment by yleflour** [comment]
FYI Adding an `"outDir": "./dist"` and setting `"emitDeclarationOnly": false` in "tsconfig.json" fixes the issue as the test runner uses the .js files from the "./dist" folder
Only seem to break with on the fly transpilation

**Comment by connor4312** [comment]
This is because we try to still parse the source naively with `acorn`. With `acorn-loose` it's often good enough but it seems like we get tripped up by this case.

While TS is technically not the only language that could transpile and get turned into JS, it's by far the most common one, so let's just ship a transpiler to deal with it properly.

**Comment by connor4312** [comment]
I played with writing a TypeScript server plugin on https://github.com/connor4312/nodejs-testing/tree/connor4312/ts-server-plugin. The advantage is this avoids bundling anything and uses the same AST's that the server will use for general editing and might already have in memory.

Unfortunately TS parses files lazily, and the actual parsing in the TS server is a lot slower (I think just because there's more going on), resulting in a few hundred ms delay when you open a file, whereas the current implementation is fairly instant, so I don't want to ship this as-is. I think the next version of TS might bring some performance improvements in that area, so I'll let that branch hang around for a little bit and see where things go. In the meantime I'll continue looking at a simpler swap from Acorn to tree-sitter's TS grammar.

**Comment by connor4312** [comment]
Fixed in https://github.com/connor4312/nodejs-testing/commit/08b5a2f4b6e64b9c1fe3dbd60628774cdde57e40, we will now use VS Code's TS language features to do the parsing
